# Generated by Django 2.2.5 on 2019-11-10 20:06

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='document',
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='document',
            field=models.FileField(null=True, upload_to=utils.upload.task_document_path, validators=[utils.validators.task_document_size, utils.validators.task_document_extension]),
        ),
    ]
