# Generated by Django 2.2.5 on 2019-11-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191110_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='stars',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
