# Generated by Django 2.2.5 on 2019-10-15 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('approximate_duration', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'standart_delivery'), (1, 'express_delivery')])),
            ],
            options={
                'abstract': False,
                'unique_together': {('type', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'food'), (1, 'clothes'), (2, 'devices')])),
                ('existance', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('name', 'price')},
            },
        ),
    ]
